apiVersion: apps/v1
kind: Deployment

metadata:
  name: hotstar-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hotstar-frontend

  template:
    metadata:
      labels:
        app: hotstar-frontend

    spec:
      containers:
        - name: hotstar-frontend

          image: sevenajay/hotstar-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
