
name: CI/CD - Build & Deploy to ECS

on:
  push:
    branches: [ master ]

permissions:
  id-token: write   # needed for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: 123456789012.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: my-app
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Register new task definition
        id: register-task
        run: |
          # This is a simple way — fetch the current task definition, patch the image, and register.
          FAMILY=my-app-task
          IMAGE_URI=${{ env.IMAGE_URI }}

          # Fetch current task def
          aws ecs describe-task-definition --task-definition $FAMILY > taskdef.json

          # Remove unnecessary fields and replace container image
          jq '.taskDefinition | del(.status,.revision,.registeredAt,.registeredBy)' taskdef.json > td.json
          jq --arg IMG "$IMAGE_URI" '.containerDefinitions[0].image=$IMG' td.json > new-taskdef.json

          aws ecs register-task-definition --cli-input-json file://new-taskdef.json

      - name: Update ECS service to use new task definition
        run: |
          CLUSTER=my-app-cluster
          SERVICE=my-app-service
          # get latest task definition arn
          NEW_TASK_DEF_ARN=$(aws ecs list-task-definitions --family-prefix my-app-task --sort DESC --max-items 1 --query 'taskDefinitionArns[0]' --output text)
          aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition $NEW_TASK_DEF_ARN



          
