jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write                # REQUIRED for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::800261073853:role/GitHubActions-Hoster-clone-role
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 123456789012.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build, tag and push
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest 123456789012.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-app:latest
          docker push 123456789012.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-app:latest
